# Generated by Django 5.0.7 on 2024-08-04 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_is_agent_user_isagent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='isAgent',
            new_name='is_agent',
        ),
    ]
